### ISSUE TITLE
Any plans to support also other OSs?

### ISSUE THREAD

**Issue by VGalata** [camilo-v/jasper#1]
Hello!

The tool looks very interesting and I would really like to try it, but are there any plans to support also other operating systems and not just the macOS?

Best,
Valentina

**Comment by camilo-v** [comment]
Hi Valentina,
Thank you for your interest in the project! For the current version, the GUI only supports macOS. I am working on a command line interface (CLI) that will run anywhere were the [Swift runtime is supported](https://www.swift.org/download/). Unfortunately, I do not have an exact date on the CLI release.



Best,

--
**Camilo**
